services:
  mongodb:
    image: mongo:latest
    container_name: fruit-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  fruit-app:
    build: .
    container_name: fruit-api-container
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb

volumes:
  mongo-data: